// Code generated by protoc-gen-go.
// source: c2s_message.proto
// DO NOT EDIT!

/*
Package C2SMessage is a generated protocol buffer package.

It is generated from these files:
	c2s_message.proto

It has these top-level messages:
	CS_Login_Req
	CS_WechatLogin_Req
	CS_BaseMessage_Req
	SC_BaseMessage_Rsp
*/
package C2SMessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// add by stefanchen
// id : msg + rsp/req + function
type SUBMSG int32

const (
	SUBMSG_invalid          SUBMSG = 0
	SUBMSG_external_gateway SUBMSG = 1
	SUBMSG_CS_Login         SUBMSG = 2
	SUBMSG_SC_Login         SUBMSG = 3
	SUBMSG_CS_Wechat_login  SUBMSG = 4
	SUBMSG_SC_Wechat_login  SUBMSG = 5
	SUBMSG_CS_BaseMessage   SUBMSG = 6
	SUBMSG_SC_BaseMessage   SUBMSG = 7
)

var SUBMSG_name = map[int32]string{
	0: "invalid",
	1: "external_gateway",
	2: "CS_Login",
	3: "SC_Login",
	4: "CS_Wechat_login",
	5: "SC_Wechat_login",
	6: "CS_BaseMessage",
	7: "SC_BaseMessage",
}
var SUBMSG_value = map[string]int32{
	"invalid":          0,
	"external_gateway": 1,
	"CS_Login":         2,
	"SC_Login":         3,
	"CS_Wechat_login":  4,
	"SC_Wechat_login":  5,
	"CS_BaseMessage":   6,
	"SC_BaseMessage":   7,
}

func (x SUBMSG) String() string {
	return proto.EnumName(SUBMSG_name, int32(x))
}
func (SUBMSG) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CS_Login_Req struct {
	DBID int32 `protobuf:"varint,1,opt,name=DBID" json:"DBID,omitempty"`
}

func (m *CS_Login_Req) Reset()                    { *m = CS_Login_Req{} }
func (m *CS_Login_Req) String() string            { return proto.CompactTextString(m) }
func (*CS_Login_Req) ProtoMessage()               {}
func (*CS_Login_Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CS_WechatLogin_Req struct {
	Openid      int32 `protobuf:"varint,1,opt,name=Openid" json:"Openid,omitempty"`
	Assesstoken int32 `protobuf:"varint,2,opt,name=Assesstoken" json:"Assesstoken,omitempty"`
}

func (m *CS_WechatLogin_Req) Reset()                    { *m = CS_WechatLogin_Req{} }
func (m *CS_WechatLogin_Req) String() string            { return proto.CompactTextString(m) }
func (*CS_WechatLogin_Req) ProtoMessage()               {}
func (*CS_WechatLogin_Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CS_BaseMessage_Req struct {
	Sid  int32  `protobuf:"varint,1,opt,name=Sid" json:"Sid,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *CS_BaseMessage_Req) Reset()                    { *m = CS_BaseMessage_Req{} }
func (m *CS_BaseMessage_Req) String() string            { return proto.CompactTextString(m) }
func (*CS_BaseMessage_Req) ProtoMessage()               {}
func (*CS_BaseMessage_Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type SC_BaseMessage_Rsp struct {
}

func (m *SC_BaseMessage_Rsp) Reset()                    { *m = SC_BaseMessage_Rsp{} }
func (m *SC_BaseMessage_Rsp) String() string            { return proto.CompactTextString(m) }
func (*SC_BaseMessage_Rsp) ProtoMessage()               {}
func (*SC_BaseMessage_Rsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*CS_Login_Req)(nil), "C2SMessage.CS_Login_Req")
	proto.RegisterType((*CS_WechatLogin_Req)(nil), "C2SMessage.CS_Wechat_login_Req")
	proto.RegisterType((*CS_BaseMessage_Req)(nil), "C2SMessage.CS_BaseMessage_Req")
	proto.RegisterType((*SC_BaseMessage_Rsp)(nil), "C2SMessage.SC_BaseMessage_Rsp")
	proto.RegisterEnum("C2SMessage.SUBMSG", SUBMSG_name, SUBMSG_value)
}

func init() { proto.RegisterFile("c2s_message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x4d, 0xff, 0xa4, 0x32, 0x0d, 0xba, 0x4e, 0x8b, 0xf4, 0x58, 0xf6, 0x24, 0x1e, 0x3c,
	0xd4, 0x9b, 0x37, 0xb3, 0x05, 0x11, 0x2c, 0x85, 0x0c, 0xe2, 0x71, 0x59, 0xdb, 0x21, 0x06, 0xe3,
	0x26, 0x76, 0x17, 0xff, 0x7c, 0x14, 0xbf, 0xad, 0x64, 0x8d, 0xc5, 0x78, 0x7b, 0xef, 0x97, 0xc9,
	0xe3, 0xbd, 0x85, 0x93, 0xcd, 0xc2, 0xe9, 0x17, 0x76, 0xce, 0xe4, 0x7c, 0x51, 0xef, 0x2a, 0x5f,
	0x21, 0xa8, 0x05, 0xad, 0x7e, 0x88, 0x94, 0x90, 0x28, 0xd2, 0x77, 0x55, 0x5e, 0x58, 0x9d, 0xf1,
	0x2b, 0x22, 0x0c, 0x96, 0xe9, 0xed, 0x72, 0x16, 0xcd, 0xa3, 0xb3, 0x61, 0x16, 0xb4, 0x5c, 0xc3,
	0x44, 0x91, 0x7e, 0xe0, 0xcd, 0x93, 0xf1, 0xba, 0xdc, 0x9f, 0x9e, 0x42, 0xbc, 0xae, 0xd9, 0x16,
	0xdb, 0xf6, 0xb8, 0x75, 0x38, 0x87, 0xf1, 0xb5, 0x73, 0xec, 0x9c, 0xaf, 0x9e, 0xd9, 0xce, 0x7a,
	0xe1, 0xe3, 0x5f, 0x24, 0xaf, 0x00, 0x15, 0xe9, 0xd4, 0x38, 0x6e, 0x6b, 0x84, 0x3c, 0x01, 0x7d,
	0xda, 0x87, 0x35, 0x32, 0x94, 0x31, 0xde, 0x84, 0x88, 0x24, 0x0b, 0x5a, 0x4e, 0x01, 0x49, 0x75,
	0xff, 0x75, 0xf5, 0xf9, 0x57, 0x04, 0x31, 0xdd, 0xa7, 0x2b, 0xba, 0xc1, 0x31, 0x8c, 0x0a, 0xfb,
	0x66, 0xca, 0x62, 0x2b, 0x0e, 0x70, 0x0a, 0x82, 0x3f, 0x3c, 0xef, 0xac, 0x29, 0x75, 0x6e, 0x3c,
	0xbf, 0x9b, 0x4f, 0x11, 0x61, 0x02, 0x87, 0xbf, 0xa3, 0x45, 0xaf, 0x71, 0xa4, 0x5a, 0xd7, 0xc7,
	0x09, 0x1c, 0xff, 0x1b, 0x2b, 0x06, 0x0d, 0x24, 0xd5, 0x85, 0x43, 0x44, 0x38, 0xea, 0xae, 0x10,
	0x71, 0xc3, 0xba, 0xed, 0xc4, 0xe8, 0x31, 0x0e, 0xaf, 0x7e, 0xf9, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0xfa, 0xf5, 0x63, 0x0e, 0x8a, 0x01, 0x00, 0x00,
}
