// Code generated by protoc-gen-go.
// source: c2s_message.proto
// DO NOT EDIT!

/*
Package C2SMessage is a generated protocol buffer package.

It is generated from these files:
	c2s_message.proto

It has these top-level messages:
	C2Sbasemessgae
	Requestlogin
	RequestWechatlogin
*/
package C2SMessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// add by stefanchen
// id : msg + rsp/req + function
type GameMessageId int32

const (
	GameMessageId_msg_invalid          GameMessageId = 0
	GameMessageId_msg_external_gateway GameMessageId = 1
	GameMessageId_msg_req_login        GameMessageId = 2
	GameMessageId_msg_rsp_login        GameMessageId = 3
	GameMessageId_msg_req_wechat_login GameMessageId = 4
	GameMessageId_msg_rsp_wechat_login GameMessageId = 5
)

var GameMessageId_name = map[int32]string{
	0: "msg_invalid",
	1: "msg_external_gateway",
	2: "msg_req_login",
	3: "msg_rsp_login",
	4: "msg_req_wechat_login",
	5: "msg_rsp_wechat_login",
}
var GameMessageId_value = map[string]int32{
	"msg_invalid":          0,
	"msg_external_gateway": 1,
	"msg_req_login":        2,
	"msg_rsp_login":        3,
	"msg_req_wechat_login": 4,
	"msg_rsp_wechat_login": 5,
}

func (x GameMessageId) String() string {
	return proto.EnumName(GameMessageId_name, int32(x))
}
func (GameMessageId) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// 路由消息
type MessageRoute int32

const (
	MessageRoute_R_SID_Invalid    MessageRoute = 0
	MessageRoute_R_SID_ESG        MessageRoute = 1
	MessageRoute_R_SID_ISG        MessageRoute = 2
	MessageRoute_R_SID_DB         MessageRoute = 3
	MessageRoute_R_SID_BigWorld   MessageRoute = 4
	MessageRoute_R_SID_Login      MessageRoute = 5
	MessageRoute_R_SID_SmallWorld MessageRoute = 6
	MessageRoute_R_SID_DBProxy    MessageRoute = 7
	MessageRoute_R_SID_Game       MessageRoute = 8
)

var MessageRoute_name = map[int32]string{
	0: "R_SID_Invalid",
	1: "R_SID_ESG",
	2: "R_SID_ISG",
	3: "R_SID_DB",
	4: "R_SID_BigWorld",
	5: "R_SID_Login",
	6: "R_SID_SmallWorld",
	7: "R_SID_DBProxy",
	8: "R_SID_Game",
}
var MessageRoute_value = map[string]int32{
	"R_SID_Invalid":    0,
	"R_SID_ESG":        1,
	"R_SID_ISG":        2,
	"R_SID_DB":         3,
	"R_SID_BigWorld":   4,
	"R_SID_Login":      5,
	"R_SID_SmallWorld": 6,
	"R_SID_DBProxy":    7,
	"R_SID_Game":       8,
}

func (x MessageRoute) String() string {
	return proto.EnumName(MessageRoute_name, int32(x))
}
func (MessageRoute) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// c2s 基础消息
type C2Sbasemessgae struct {
	Baseid int32  `protobuf:"varint,1,opt,name=Baseid" json:"Baseid,omitempty"`
	Sid    int32  `protobuf:"varint,2,opt,name=Sid" json:"Sid,omitempty"`
	Data   []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (m *C2Sbasemessgae) Reset()                    { *m = C2Sbasemessgae{} }
func (m *C2Sbasemessgae) String() string            { return proto.CompactTextString(m) }
func (*C2Sbasemessgae) ProtoMessage()               {}
func (*C2Sbasemessgae) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Requestlogin struct {
	DBID int32 `protobuf:"varint,1,opt,name=DBID" json:"DBID,omitempty"`
}

func (m *Requestlogin) Reset()                    { *m = Requestlogin{} }
func (m *Requestlogin) String() string            { return proto.CompactTextString(m) }
func (*Requestlogin) ProtoMessage()               {}
func (*Requestlogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type RequestWechatlogin struct {
	Openid      int32 `protobuf:"varint,1,opt,name=Openid" json:"Openid,omitempty"`
	Assesstoken int32 `protobuf:"varint,2,opt,name=Assesstoken" json:"Assesstoken,omitempty"`
}

func (m *RequestWechatlogin) Reset()                    { *m = RequestWechatlogin{} }
func (m *RequestWechatlogin) String() string            { return proto.CompactTextString(m) }
func (*RequestWechatlogin) ProtoMessage()               {}
func (*RequestWechatlogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*C2Sbasemessgae)(nil), "C2SMessage.C2sbasemessgae")
	proto.RegisterType((*Requestlogin)(nil), "C2SMessage.Requestlogin")
	proto.RegisterType((*RequestWechatlogin)(nil), "C2SMessage.RequestWechatlogin")
	proto.RegisterEnum("C2SMessage.GameMessageId", GameMessageId_name, GameMessageId_value)
	proto.RegisterEnum("C2SMessage.MessageRoute", MessageRoute_name, MessageRoute_value)
}

func init() { proto.RegisterFile("c2s_message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0x92, 0x4d, 0x6e, 0xe2, 0x40,
	0x10, 0x85, 0xc7, 0x18, 0x3c, 0x4c, 0xf1, 0xd7, 0x94, 0x10, 0xf2, 0x12, 0x79, 0x85, 0x58, 0xcc,
	0x82, 0x39, 0xc1, 0x18, 0x47, 0xc8, 0x52, 0x42, 0x22, 0x7b, 0xc1, 0xd2, 0x6a, 0x70, 0xc9, 0xb1,
	0xe2, 0x3f, 0xdc, 0x26, 0xc0, 0x45, 0x72, 0x8a, 0x1c, 0x32, 0xb2, 0xbb, 0x81, 0x64, 0x57, 0xef,
	0xab, 0xe7, 0x7e, 0xaf, 0x24, 0xc3, 0x78, 0xbf, 0x14, 0x41, 0x4a, 0x42, 0xf0, 0x88, 0xfe, 0x16,
	0x65, 0x5e, 0xe5, 0x08, 0xab, 0xa5, 0xff, 0x24, 0x89, 0xb5, 0x81, 0xe1, 0x6a, 0x29, 0x76, 0x5c,
	0x50, 0xed, 0x89, 0x38, 0xe1, 0x14, 0x0c, 0x9b, 0x0b, 0x8a, 0x43, 0x53, 0x9b, 0x69, 0xf3, 0x8e,
	0xa7, 0x14, 0x32, 0xd0, 0xfd, 0x38, 0x34, 0x5b, 0x0d, 0xac, 0x47, 0x44, 0x68, 0x3b, 0xbc, 0xe2,
	0xa6, 0x3e, 0xd3, 0xe6, 0x7d, 0xaf, 0x99, 0x2d, 0x0b, 0xfa, 0x1e, 0x1d, 0x8e, 0x24, 0xaa, 0x24,
	0x8f, 0xe2, 0xac, 0xf1, 0xd8, 0xae, 0xa3, 0xde, 0x6a, 0x66, 0x6b, 0x03, 0xa8, 0x3c, 0x5b, 0xda,
	0xbf, 0x72, 0xe5, 0x9c, 0x82, 0xf1, 0x5c, 0x50, 0x76, 0xcf, 0x95, 0x0a, 0x67, 0xd0, 0xfb, 0x2f,
	0x04, 0x09, 0x51, 0xe5, 0x6f, 0x94, 0xa9, 0xfc, 0xef, 0x68, 0xf1, 0xa1, 0xc1, 0x28, 0xe2, 0x29,
	0x5d, 0xcf, 0x0c, 0xe2, 0x10, 0x47, 0xd0, 0x4b, 0x45, 0x14, 0xc4, 0xd9, 0x3b, 0x4f, 0xe2, 0x90,
	0xfd, 0x42, 0x13, 0x26, 0x35, 0xa0, 0x73, 0x45, 0x65, 0xc6, 0x93, 0x20, 0xe2, 0x15, 0x9d, 0xf8,
	0x85, 0x69, 0x38, 0x86, 0x41, 0xbd, 0x29, 0xe9, 0x10, 0x34, 0x4d, 0x58, 0xeb, 0x86, 0x44, 0xa1,
	0x90, 0x7e, 0xfd, 0xbe, 0x76, 0x9d, 0x9a, 0xd6, 0x6a, 0xd3, 0xbe, 0x6d, 0x44, 0xf1, 0x73, 0xd3,
	0x59, 0x7c, 0x6a, 0x30, 0xb8, 0x76, 0x2a, 0xf3, 0x63, 0x45, 0xf5, 0xc3, 0x5e, 0xe0, 0xbb, 0x4e,
	0xe0, 0xde, 0x8a, 0x0d, 0xe0, 0x8f, 0x44, 0x0f, 0xfe, 0x9a, 0x69, 0x77, 0xe9, 0xfa, 0x6b, 0xd6,
	0xc2, 0x3e, 0x74, 0xa5, 0x74, 0x6c, 0xa6, 0x23, 0xc2, 0x50, 0x2a, 0x3b, 0x8e, 0xb6, 0x79, 0x99,
	0x84, 0xac, 0x5d, 0x5f, 0x2a, 0xd9, 0xa3, 0x4c, 0xc5, 0x09, 0x30, 0x09, 0xfc, 0x94, 0x27, 0x89,
	0xb4, 0x19, 0xf7, 0x64, 0xc7, 0x7e, 0x29, 0xf3, 0xf3, 0x85, 0xfd, 0xc6, 0x21, 0x80, 0x44, 0x6b,
	0x9e, 0x12, 0xeb, 0xee, 0x8c, 0xe6, 0xf7, 0xf8, 0xf7, 0x15, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xe1,
	0x07, 0x52, 0x33, 0x02, 0x00, 0x00,
}
