// Code generated by protoc-gen-go. DO NOT EDIT.
// source: c2s_message.proto

package C2SMessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// add by stefanchen
// id : msg + rsp/req + function
type GameMessageId int32

const (
	GameMessageId_msg_invalid          GameMessageId = 0
	GameMessageId_msg_external_gateway GameMessageId = 1
	GameMessageId_msg_req_login        GameMessageId = 2
	GameMessageId_msg_rsp_login        GameMessageId = 3
	GameMessageId_msg_req_wechat_login GameMessageId = 4
	GameMessageId_msg_rsp_wechat_login GameMessageId = 5
)

var GameMessageId_name = map[int32]string{
	0: "msg_invalid",
	1: "msg_external_gateway",
	2: "msg_req_login",
	3: "msg_rsp_login",
	4: "msg_req_wechat_login",
	5: "msg_rsp_wechat_login",
}
var GameMessageId_value = map[string]int32{
	"msg_invalid":          0,
	"msg_external_gateway": 1,
	"msg_req_login":        2,
	"msg_rsp_login":        3,
	"msg_req_wechat_login": 4,
	"msg_rsp_wechat_login": 5,
}

func (x GameMessageId) Enum() *GameMessageId {
	p := new(GameMessageId)
	*p = x
	return p
}
func (x GameMessageId) String() string {
	return proto.EnumName(GameMessageId_name, int32(x))
}
func (x *GameMessageId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GameMessageId_value, data, "GameMessageId")
	if err != nil {
		return err
	}
	*x = GameMessageId(value)
	return nil
}
func (GameMessageId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2s_message_b7100f983ddff536, []int{0}
}

// 路由消息
type MessageRoute int32

const (
	MessageRoute_R_SID_ESG        MessageRoute = 1
	MessageRoute_R_SID_ISG        MessageRoute = 2
	MessageRoute_R_SID_DB         MessageRoute = 3
	MessageRoute_R_SID_BigWorld   MessageRoute = 4
	MessageRoute_R_SID_Login      MessageRoute = 5
	MessageRoute_R_SID_SmallWorld MessageRoute = 6
	MessageRoute_R_SID_DBProxy    MessageRoute = 7
	MessageRoute_R_SID_Game       MessageRoute = 8
)

var MessageRoute_name = map[int32]string{
	1: "R_SID_ESG",
	2: "R_SID_ISG",
	3: "R_SID_DB",
	4: "R_SID_BigWorld",
	5: "R_SID_Login",
	6: "R_SID_SmallWorld",
	7: "R_SID_DBProxy",
	8: "R_SID_Game",
}
var MessageRoute_value = map[string]int32{
	"R_SID_ESG":        1,
	"R_SID_ISG":        2,
	"R_SID_DB":         3,
	"R_SID_BigWorld":   4,
	"R_SID_Login":      5,
	"R_SID_SmallWorld": 6,
	"R_SID_DBProxy":    7,
	"R_SID_Game":       8,
}

func (x MessageRoute) Enum() *MessageRoute {
	p := new(MessageRoute)
	*p = x
	return p
}
func (x MessageRoute) String() string {
	return proto.EnumName(MessageRoute_name, int32(x))
}
func (x *MessageRoute) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MessageRoute_value, data, "MessageRoute")
	if err != nil {
		return err
	}
	*x = MessageRoute(value)
	return nil
}
func (MessageRoute) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c2s_message_b7100f983ddff536, []int{1}
}

// c2s 基础消息
type C2Sbasemessgae struct {
	Baseid               *int32   `protobuf:"varint,1,req,name=baseid" json:"baseid,omitempty"`
	Sid                  *int32   `protobuf:"varint,2,req,name=sid" json:"sid,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2Sbasemessgae) Reset()         { *m = C2Sbasemessgae{} }
func (m *C2Sbasemessgae) String() string { return proto.CompactTextString(m) }
func (*C2Sbasemessgae) ProtoMessage()    {}
func (*C2Sbasemessgae) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2s_message_b7100f983ddff536, []int{0}
}
func (m *C2Sbasemessgae) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2Sbasemessgae.Unmarshal(m, b)
}
func (m *C2Sbasemessgae) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2Sbasemessgae.Marshal(b, m, deterministic)
}
func (dst *C2Sbasemessgae) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2Sbasemessgae.Merge(dst, src)
}
func (m *C2Sbasemessgae) XXX_Size() int {
	return xxx_messageInfo_C2Sbasemessgae.Size(m)
}
func (m *C2Sbasemessgae) XXX_DiscardUnknown() {
	xxx_messageInfo_C2Sbasemessgae.DiscardUnknown(m)
}

var xxx_messageInfo_C2Sbasemessgae proto.InternalMessageInfo

func (m *C2Sbasemessgae) GetBaseid() int32 {
	if m != nil && m.Baseid != nil {
		return *m.Baseid
	}
	return 0
}

func (m *C2Sbasemessgae) GetSid() int32 {
	if m != nil && m.Sid != nil {
		return *m.Sid
	}
	return 0
}

func (m *C2Sbasemessgae) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Requestlogin struct {
	Dbid                 *int32   `protobuf:"varint,1,req,name=dbid" json:"dbid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Requestlogin) Reset()         { *m = Requestlogin{} }
func (m *Requestlogin) String() string { return proto.CompactTextString(m) }
func (*Requestlogin) ProtoMessage()    {}
func (*Requestlogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2s_message_b7100f983ddff536, []int{1}
}
func (m *Requestlogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Requestlogin.Unmarshal(m, b)
}
func (m *Requestlogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Requestlogin.Marshal(b, m, deterministic)
}
func (dst *Requestlogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Requestlogin.Merge(dst, src)
}
func (m *Requestlogin) XXX_Size() int {
	return xxx_messageInfo_Requestlogin.Size(m)
}
func (m *Requestlogin) XXX_DiscardUnknown() {
	xxx_messageInfo_Requestlogin.DiscardUnknown(m)
}

var xxx_messageInfo_Requestlogin proto.InternalMessageInfo

func (m *Requestlogin) GetDbid() int32 {
	if m != nil && m.Dbid != nil {
		return *m.Dbid
	}
	return 0
}

type RequestWechatlogin struct {
	Openid               *int32   `protobuf:"varint,1,req,name=openid" json:"openid,omitempty"`
	Assesstoken          *int32   `protobuf:"varint,2,req,name=assesstoken" json:"assesstoken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestWechatlogin) Reset()         { *m = RequestWechatlogin{} }
func (m *RequestWechatlogin) String() string { return proto.CompactTextString(m) }
func (*RequestWechatlogin) ProtoMessage()    {}
func (*RequestWechatlogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_c2s_message_b7100f983ddff536, []int{2}
}
func (m *RequestWechatlogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestWechatlogin.Unmarshal(m, b)
}
func (m *RequestWechatlogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestWechatlogin.Marshal(b, m, deterministic)
}
func (dst *RequestWechatlogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestWechatlogin.Merge(dst, src)
}
func (m *RequestWechatlogin) XXX_Size() int {
	return xxx_messageInfo_RequestWechatlogin.Size(m)
}
func (m *RequestWechatlogin) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestWechatlogin.DiscardUnknown(m)
}

var xxx_messageInfo_RequestWechatlogin proto.InternalMessageInfo

func (m *RequestWechatlogin) GetOpenid() int32 {
	if m != nil && m.Openid != nil {
		return *m.Openid
	}
	return 0
}

func (m *RequestWechatlogin) GetAssesstoken() int32 {
	if m != nil && m.Assesstoken != nil {
		return *m.Assesstoken
	}
	return 0
}

func init() {
	proto.RegisterType((*C2Sbasemessgae)(nil), "C2SMessage.c2sbasemessgae")
	proto.RegisterType((*Requestlogin)(nil), "C2SMessage.requestlogin")
	proto.RegisterType((*RequestWechatlogin)(nil), "C2SMessage.requestWechatlogin")
	proto.RegisterEnum("C2SMessage.GameMessageId", GameMessageId_name, GameMessageId_value)
	proto.RegisterEnum("C2SMessage.MessageRoute", MessageRoute_name, MessageRoute_value)
}

func init() { proto.RegisterFile("c2s_message.proto", fileDescriptor_c2s_message_b7100f983ddff536) }

var fileDescriptor_c2s_message_b7100f983ddff536 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x8f, 0xcf, 0x6e, 0xf2, 0x30,
	0x10, 0xc4, 0xbf, 0x24, 0xc0, 0x47, 0x97, 0x7f, 0x66, 0x85, 0x50, 0x8e, 0x28, 0x27, 0xc4, 0xa1,
	0x07, 0x1e, 0x81, 0x52, 0x21, 0xa4, 0x16, 0x55, 0xe4, 0xc0, 0x31, 0x32, 0x64, 0x95, 0x46, 0x4d,
	0xe2, 0x10, 0x9b, 0x02, 0x2f, 0x52, 0xa9, 0x6f, 0x5b, 0x39, 0x4e, 0xa0, 0xbd, 0xed, 0xfc, 0x66,
	0xec, 0x9d, 0x85, 0xe1, 0x61, 0x2e, 0x83, 0x94, 0xa4, 0xe4, 0x11, 0x3d, 0xe6, 0x85, 0x50, 0x02,
	0xe1, 0x69, 0xee, 0xbf, 0x1a, 0xe2, 0x6d, 0xa0, 0x7f, 0x98, 0xcb, 0x3d, 0x97, 0xa4, 0x33, 0x11,
	0x27, 0x1c, 0x43, 0x4b, 0xcb, 0x38, 0x74, 0xad, 0x89, 0x3d, 0x6d, 0x6e, 0x2b, 0x85, 0x0c, 0x1c,
	0x19, 0x87, 0xae, 0x5d, 0x42, 0x3d, 0x22, 0x42, 0x23, 0xe4, 0x8a, 0xbb, 0xce, 0xc4, 0x9e, 0x76,
	0xb7, 0xe5, 0xec, 0x79, 0xd0, 0x2d, 0xe8, 0x78, 0x22, 0xa9, 0x12, 0x11, 0xc5, 0x59, 0x99, 0xd9,
	0xdf, 0xfe, 0x2a, 0x67, 0x6f, 0x03, 0x58, 0x65, 0x76, 0x74, 0x78, 0xe7, 0x55, 0x72, 0x0c, 0x2d,
	0x91, 0x53, 0x76, 0xdf, 0x6b, 0x14, 0x4e, 0xa0, 0xc3, 0xa5, 0x24, 0x29, 0x95, 0xf8, 0xa0, 0xac,
	0xda, 0xff, 0x1b, 0xcd, 0xbe, 0x2c, 0x18, 0x44, 0x3c, 0xa5, 0xfa, 0xcc, 0x20, 0x0e, 0x71, 0x00,
	0x9d, 0x54, 0x46, 0x41, 0x9c, 0x7d, 0xf2, 0x24, 0x0e, 0xd9, 0x3f, 0x74, 0x61, 0xa4, 0x01, 0x5d,
	0x14, 0x15, 0x19, 0x4f, 0x82, 0x88, 0x2b, 0x3a, 0xf3, 0x2b, 0xb3, 0x70, 0x08, 0x3d, 0xed, 0x14,
	0x74, 0x0c, 0xca, 0x26, 0xcc, 0xbe, 0x21, 0x99, 0x57, 0xc8, 0xa9, 0xdf, 0xeb, 0xd4, 0xb9, 0x6c,
	0x5d, 0x39, 0x8d, 0x9b, 0x23, 0xf3, 0xbf, 0x4e, 0x73, 0xf6, 0x6d, 0x41, 0xaf, 0xee, 0x54, 0x88,
	0x93, 0x22, 0xec, 0xc1, 0xc3, 0x36, 0xf0, 0xd7, 0xcb, 0xe0, 0xd9, 0x5f, 0x31, 0xeb, 0x2e, 0xd7,
	0xfe, 0x8a, 0xd9, 0xd8, 0x85, 0xb6, 0x91, 0xcb, 0x05, 0x73, 0x10, 0xa1, 0x6f, 0xd4, 0x22, 0x8e,
	0x76, 0xa2, 0x48, 0x42, 0xd6, 0xd0, 0x67, 0x19, 0xf6, 0x62, 0x56, 0xe0, 0x08, 0x98, 0x01, 0x7e,
	0xca, 0x93, 0xc4, 0xc4, 0x5a, 0xba, 0x7f, 0xfd, 0xd1, 0x5b, 0x21, 0x2e, 0x57, 0xf6, 0x1f, 0xfb,
	0x00, 0x06, 0xad, 0x78, 0x4a, 0xac, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0xb3, 0x40, 0x57, 0x98,
	0x18, 0x02, 0x00, 0x00,
}
