// Code generated by protoc-gen-go. DO NOT EDIT.
// source: s2s_message.proto

package S2SMessage

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServerMessageId int32

const (
	ServerMessageId_msg_invalid ServerMessageId = 0
)

var ServerMessageId_name = map[int32]string{
	0: "msg_invalid",
}
var ServerMessageId_value = map[string]int32{
	"msg_invalid": 0,
}

func (x ServerMessageId) Enum() *ServerMessageId {
	p := new(ServerMessageId)
	*p = x
	return p
}
func (x ServerMessageId) String() string {
	return proto.EnumName(ServerMessageId_name, int32(x))
}
func (x *ServerMessageId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ServerMessageId_value, data, "ServerMessageId")
	if err != nil {
		return err
	}
	*x = ServerMessageId(value)
	return nil
}
func (ServerMessageId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_s2s_message_a32a36efd734e5ff, []int{0}
}

type ServerId int32

const (
	ServerId_SID_ESG        ServerId = 1
	ServerId_SID_ISG        ServerId = 2
	ServerId_SID_DB         ServerId = 3
	ServerId_SID_BigWorld   ServerId = 4
	ServerId_SID_Login      ServerId = 5
	ServerId_SID_SmallWorld ServerId = 6
	ServerId_SID_DBProxy    ServerId = 7
	ServerId_SID_Game       ServerId = 8
)

var ServerId_name = map[int32]string{
	1: "SID_ESG",
	2: "SID_ISG",
	3: "SID_DB",
	4: "SID_BigWorld",
	5: "SID_Login",
	6: "SID_SmallWorld",
	7: "SID_DBProxy",
	8: "SID_Game",
}
var ServerId_value = map[string]int32{
	"SID_ESG":        1,
	"SID_ISG":        2,
	"SID_DB":         3,
	"SID_BigWorld":   4,
	"SID_Login":      5,
	"SID_SmallWorld": 6,
	"SID_DBProxy":    7,
	"SID_Game":       8,
}

func (x ServerId) Enum() *ServerId {
	p := new(ServerId)
	*p = x
	return p
}
func (x ServerId) String() string {
	return proto.EnumName(ServerId_name, int32(x))
}
func (x *ServerId) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ServerId_value, data, "ServerId")
	if err != nil {
		return err
	}
	*x = ServerId(value)
	return nil
}
func (ServerId) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_s2s_message_a32a36efd734e5ff, []int{1}
}

// route c2s消息路由
type C2SMsgRoute struct {
	Operid               *int32   `protobuf:"varint,1,req,name=operid" json:"operid,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2SMsgRoute) Reset()         { *m = C2SMsgRoute{} }
func (m *C2SMsgRoute) String() string { return proto.CompactTextString(m) }
func (*C2SMsgRoute) ProtoMessage()    {}
func (*C2SMsgRoute) Descriptor() ([]byte, []int) {
	return fileDescriptor_s2s_message_a32a36efd734e5ff, []int{0}
}
func (m *C2SMsgRoute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2SMsgRoute.Unmarshal(m, b)
}
func (m *C2SMsgRoute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2SMsgRoute.Marshal(b, m, deterministic)
}
func (dst *C2SMsgRoute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2SMsgRoute.Merge(dst, src)
}
func (m *C2SMsgRoute) XXX_Size() int {
	return xxx_messageInfo_C2SMsgRoute.Size(m)
}
func (m *C2SMsgRoute) XXX_DiscardUnknown() {
	xxx_messageInfo_C2SMsgRoute.DiscardUnknown(m)
}

var xxx_messageInfo_C2SMsgRoute proto.InternalMessageInfo

func (m *C2SMsgRoute) GetOperid() int32 {
	if m != nil && m.Operid != nil {
		return *m.Operid
	}
	return 0
}

func (m *C2SMsgRoute) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

// s2s 服务器间 基础消息
type S2Sbasemessage struct {
	Srcid                *int32   `protobuf:"varint,1,req,name=srcid" json:"srcid,omitempty"`
	Dstid                *int32   `protobuf:"varint,2,req,name=dstid" json:"dstid,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,req,name=data" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S2Sbasemessage) Reset()         { *m = S2Sbasemessage{} }
func (m *S2Sbasemessage) String() string { return proto.CompactTextString(m) }
func (*S2Sbasemessage) ProtoMessage()    {}
func (*S2Sbasemessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_s2s_message_a32a36efd734e5ff, []int{1}
}
func (m *S2Sbasemessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S2Sbasemessage.Unmarshal(m, b)
}
func (m *S2Sbasemessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S2Sbasemessage.Marshal(b, m, deterministic)
}
func (dst *S2Sbasemessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S2Sbasemessage.Merge(dst, src)
}
func (m *S2Sbasemessage) XXX_Size() int {
	return xxx_messageInfo_S2Sbasemessage.Size(m)
}
func (m *S2Sbasemessage) XXX_DiscardUnknown() {
	xxx_messageInfo_S2Sbasemessage.DiscardUnknown(m)
}

var xxx_messageInfo_S2Sbasemessage proto.InternalMessageInfo

func (m *S2Sbasemessage) GetSrcid() int32 {
	if m != nil && m.Srcid != nil {
		return *m.Srcid
	}
	return 0
}

func (m *S2Sbasemessage) GetDstid() int32 {
	if m != nil && m.Dstid != nil {
		return *m.Dstid
	}
	return 0
}

func (m *S2Sbasemessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*C2SMsgRoute)(nil), "S2SMessage.c2s_msg_route")
	proto.RegisterType((*S2Sbasemessage)(nil), "S2SMessage.s2sbasemessage")
	proto.RegisterEnum("S2SMessage.ServerMessageId", ServerMessageId_name, ServerMessageId_value)
	proto.RegisterEnum("S2SMessage.ServerId", ServerId_name, ServerId_value)
}

func init() { proto.RegisterFile("s2s_message.proto", fileDescriptor_s2s_message_a32a36efd734e5ff) }

var fileDescriptor_s2s_message_a32a36efd734e5ff = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x8e, 0xc1, 0x6a, 0xc2, 0x40,
	0x10, 0x86, 0x9b, 0x68, 0xa2, 0x8e, 0xd1, 0xae, 0x43, 0x29, 0x1e, 0x45, 0x7a, 0x10, 0x0f, 0x3d,
	0xe4, 0xda, 0x9b, 0x58, 0x82, 0xd0, 0x82, 0x64, 0x0f, 0x3d, 0x86, 0xad, 0xbb, 0x84, 0x85, 0xc4,
	0x95, 0x9d, 0x54, 0xda, 0x07, 0xe8, 0x7b, 0x97, 0x31, 0xd1, 0xde, 0xe6, 0xfb, 0xf8, 0xe7, 0x9f,
	0x81, 0x19, 0xa5, 0x54, 0xd4, 0x86, 0x48, 0x95, 0xe6, 0xf9, 0xe4, 0x5d, 0xe3, 0x10, 0x64, 0x2a,
	0xdf, 0x5b, 0xb3, 0x7c, 0x81, 0xc9, 0x81, 0x03, 0x54, 0x16, 0xde, 0x7d, 0x35, 0x06, 0x1f, 0x21,
	0x76, 0x27, 0xe3, 0xad, 0x9e, 0x07, 0x8b, 0x70, 0x15, 0xe5, 0x1d, 0x21, 0x42, 0x5f, 0xab, 0x46,
	0xcd, 0xc3, 0x45, 0xb8, 0x4a, 0xf2, 0xcb, 0xbc, 0xdc, 0xc3, 0x94, 0x52, 0xfa, 0x54, 0x64, 0xba,
	0x03, 0xf8, 0x00, 0x11, 0xf9, 0xc3, 0x6d, 0xb9, 0x05, 0xb6, 0x9a, 0x1a, 0xab, 0x2f, 0xcb, 0x51,
	0xde, 0xc2, 0xad, 0xb1, 0xf7, 0xdf, 0xb8, 0x7e, 0x82, 0x19, 0x19, 0x7f, 0x36, 0xfe, 0xfa, 0x72,
	0x61, 0x35, 0xde, 0xc3, 0x98, 0xff, 0xb3, 0xc7, 0xb3, 0xaa, 0xac, 0x16, 0x77, 0xeb, 0xdf, 0x00,
	0x46, 0x5d, 0xcc, 0x6a, 0x1c, 0xc3, 0x40, 0xee, 0xb6, 0xc5, 0xab, 0xcc, 0x44, 0x70, 0x85, 0x9d,
	0xcc, 0x44, 0x88, 0x00, 0x31, 0xc3, 0x76, 0x23, 0x7a, 0x28, 0x20, 0xe1, 0x79, 0x63, 0xcb, 0x0f,
	0xe7, 0x2b, 0x2d, 0xfa, 0x38, 0x81, 0x11, 0x9b, 0x37, 0x57, 0xda, 0xa3, 0x88, 0x10, 0x61, 0xca,
	0x28, 0x6b, 0x55, 0x55, 0x6d, 0x24, 0xe6, 0xcb, 0x6d, 0xc1, 0xde, 0xbb, 0xef, 0x1f, 0x31, 0xc0,
	0x04, 0x86, 0x2c, 0x32, 0x55, 0x1b, 0x31, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x46, 0x26, 0x93,
	0x70, 0x5c, 0x01, 0x00, 0x00,
}
