/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.MSG_Player.SC_PlayerInfo_Rsp');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.MSG_Player.BaseMoney_Repeat');
goog.require('proto.MSG_Player.BasePlayerInfo_Repeat');

goog.forwardDeclare('proto.MSG_Player.ErrorCode');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.MSG_Player.SC_PlayerInfo_Rsp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.MSG_Player.SC_PlayerInfo_Rsp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.MSG_Player.SC_PlayerInfo_Rsp.displayName = 'proto.MSG_Player.SC_PlayerInfo_Rsp';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.toObject = function(opt_includeInstance) {
  return proto.MSG_Player.SC_PlayerInfo_Rsp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.MSG_Player.SC_PlayerInfo_Rsp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.toObject = function(includeInstance, msg) {
  var f, obj = {
    baseinfo: (f = msg.getBaseinfo()) && proto.MSG_Player.BasePlayerInfo_Repeat.toObject(includeInstance, f),
    basemoney: (f = msg.getBasemoney()) && proto.MSG_Player.BaseMoney_Repeat.toObject(includeInstance, f),
    ret: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.MSG_Player.SC_PlayerInfo_Rsp}
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.MSG_Player.SC_PlayerInfo_Rsp;
  return proto.MSG_Player.SC_PlayerInfo_Rsp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.MSG_Player.SC_PlayerInfo_Rsp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.MSG_Player.SC_PlayerInfo_Rsp}
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.MSG_Player.BasePlayerInfo_Repeat;
      reader.readMessage(value,proto.MSG_Player.BasePlayerInfo_Repeat.deserializeBinaryFromReader);
      msg.setBaseinfo(value);
      break;
    case 2:
      var value = new proto.MSG_Player.BaseMoney_Repeat;
      reader.readMessage(value,proto.MSG_Player.BaseMoney_Repeat.deserializeBinaryFromReader);
      msg.setBasemoney(value);
      break;
    case 3:
      var value = /** @type {!proto.MSG_Player.ErrorCode} */ (reader.readEnum());
      msg.setRet(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.MSG_Player.SC_PlayerInfo_Rsp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.MSG_Player.SC_PlayerInfo_Rsp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBaseinfo();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.MSG_Player.BasePlayerInfo_Repeat.serializeBinaryToWriter
    );
  }
  f = message.getBasemoney();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.MSG_Player.BaseMoney_Repeat.serializeBinaryToWriter
    );
  }
  f = message.getRet();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional BasePlayerInfo_Repeat baseInfo = 1;
 * @return {?proto.MSG_Player.BasePlayerInfo_Repeat}
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.getBaseinfo = function() {
  return /** @type{?proto.MSG_Player.BasePlayerInfo_Repeat} */ (
    jspb.Message.getWrapperField(this, proto.MSG_Player.BasePlayerInfo_Repeat, 1));
};


/** @param {?proto.MSG_Player.BasePlayerInfo_Repeat|undefined} value */
proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.setBaseinfo = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.clearBaseinfo = function() {
  this.setBaseinfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.hasBaseinfo = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional BaseMoney_Repeat baseMoney = 2;
 * @return {?proto.MSG_Player.BaseMoney_Repeat}
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.getBasemoney = function() {
  return /** @type{?proto.MSG_Player.BaseMoney_Repeat} */ (
    jspb.Message.getWrapperField(this, proto.MSG_Player.BaseMoney_Repeat, 2));
};


/** @param {?proto.MSG_Player.BaseMoney_Repeat|undefined} value */
proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.setBasemoney = function(value) {
  jspb.Message.setWrapperField(this, 2, value);
};


proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.clearBasemoney = function() {
  this.setBasemoney(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.hasBasemoney = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional ErrorCode Ret = 3;
 * @return {!proto.MSG_Player.ErrorCode}
 */
proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.getRet = function() {
  return /** @type {!proto.MSG_Player.ErrorCode} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.MSG_Player.ErrorCode} value */
proto.MSG_Player.SC_PlayerInfo_Rsp.prototype.setRet = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};


