// Code generated by protoc-gen-go.
// source: MSG_Login.proto
// DO NOT EDIT!

/*
Package MSG_Login is a generated protocol buffer package.

It is generated from these files:
	MSG_Login.proto

It has these top-level messages:
	CS_UserBind_Req
	CS_UserRegister_Req
	SC_UserRegister_Rsp
*/
package MSG_Login

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// add by stefanchen
// server
type SUBMSG int32

const (
	SUBMSG_Begin           SUBMSG = 0
	SUBMSG_CS_UserBind     SUBMSG = 1
	SUBMSG_SC_UserBind     SUBMSG = 2
	SUBMSG_CS_UserRegister SUBMSG = 3
	SUBMSG_SC_UserRegister SUBMSG = 4
)

var SUBMSG_name = map[int32]string{
	0: "Begin",
	1: "CS_UserBind",
	2: "SC_UserBind",
	3: "CS_UserRegister",
	4: "SC_UserRegister",
}
var SUBMSG_value = map[string]int32{
	"Begin":           0,
	"CS_UserBind":     1,
	"SC_UserBind":     2,
	"CS_UserRegister": 3,
	"SC_UserRegister": 4,
}

func (x SUBMSG) String() string {
	return proto.EnumName(SUBMSG_name, int32(x))
}
func (SUBMSG) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ErrorCode int32

const (
	ErrorCode_Invalid ErrorCode = 0
	ErrorCode_Success ErrorCode = 1
	ErrorCode_Fail    ErrorCode = 2
)

var ErrorCode_name = map[int32]string{
	0: "Invalid",
	1: "Success",
	2: "Fail",
}
var ErrorCode_value = map[string]int32{
	"Invalid": 0,
	"Success": 1,
	"Fail":    2,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// CS_UserBind
type CS_UserBind_Req struct {
	Account string `protobuf:"bytes,1,opt,name=Account" json:"Account,omitempty"`
	Passwd  string `protobuf:"bytes,2,opt,name=Passwd" json:"Passwd,omitempty"`
}

func (m *CS_UserBind_Req) Reset()                    { *m = CS_UserBind_Req{} }
func (m *CS_UserBind_Req) String() string            { return proto.CompactTextString(m) }
func (*CS_UserBind_Req) ProtoMessage()               {}
func (*CS_UserBind_Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// CS_UserRegister
type CS_UserRegister_Req struct {
	Account      string `protobuf:"bytes,1,opt,name=Account" json:"Account,omitempty"`
	Passwd       string `protobuf:"bytes,2,opt,name=Passwd" json:"Passwd,omitempty"`
	DeviceSerial string `protobuf:"bytes,3,opt,name=DeviceSerial" json:"DeviceSerial,omitempty"`
	DeviceName   string `protobuf:"bytes,4,opt,name=DeviceName" json:"DeviceName,omitempty"`
}

func (m *CS_UserRegister_Req) Reset()                    { *m = CS_UserRegister_Req{} }
func (m *CS_UserRegister_Req) String() string            { return proto.CompactTextString(m) }
func (*CS_UserRegister_Req) ProtoMessage()               {}
func (*CS_UserRegister_Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// SC_UserRegister
type SC_UserRegister_Rsp struct {
	Ret ErrorCode `protobuf:"varint,1,opt,name=Ret,enum=MSG_Login.ErrorCode" json:"Ret,omitempty"`
}

func (m *SC_UserRegister_Rsp) Reset()                    { *m = SC_UserRegister_Rsp{} }
func (m *SC_UserRegister_Rsp) String() string            { return proto.CompactTextString(m) }
func (*SC_UserRegister_Rsp) ProtoMessage()               {}
func (*SC_UserRegister_Rsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*CS_UserBind_Req)(nil), "MSG_Login.CS_UserBind_Req")
	proto.RegisterType((*CS_UserRegister_Req)(nil), "MSG_Login.CS_UserRegister_Req")
	proto.RegisterType((*SC_UserRegister_Rsp)(nil), "MSG_Login.SC_UserRegister_Rsp")
	proto.RegisterEnum("MSG_Login.SUBMSG", SUBMSG_name, SUBMSG_value)
	proto.RegisterEnum("MSG_Login.ErrorCode", ErrorCode_name, ErrorCode_value)
}

func init() { proto.RegisterFile("MSG_Login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x91, 0xcf, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0x9b, 0x1f, 0xdf, 0xf4, 0x9b, 0xa9, 0x98, 0x65, 0x22, 0x92, 0x93, 0x48, 0x0e, 0x22,
	0x3d, 0x54, 0xd0, 0xb3, 0x07, 0x13, 0xb5, 0x08, 0x56, 0x24, 0x4b, 0xcf, 0x21, 0x26, 0x43, 0x58,
	0x88, 0xd9, 0xba, 0x9b, 0xd6, 0x3f, 0xc2, 0x7f, 0x5a, 0x92, 0xa6, 0xb1, 0xf6, 0xe8, 0xf1, 0x7d,
	0x66, 0x98, 0xf7, 0x78, 0x03, 0xde, 0x82, 0xcf, 0xd3, 0x67, 0x59, 0x8a, 0x7a, 0xb6, 0x52, 0xb2,
	0x91, 0xe8, 0x0e, 0x20, 0x8c, 0xc1, 0x8b, 0x79, 0xba, 0xd4, 0xa4, 0x22, 0x51, 0x17, 0x69, 0x42,
	0x1f, 0x18, 0xc0, 0xf8, 0x2e, 0xcf, 0xe5, 0xba, 0x6e, 0x02, 0xe3, 0xdc, 0xb8, 0x74, 0x93, 0x9d,
	0xc4, 0x53, 0x70, 0x5e, 0x33, 0xad, 0x3f, 0x8b, 0xc0, 0xec, 0x06, 0xbd, 0x0a, 0xbf, 0x0c, 0xf0,
	0xfb, 0x2b, 0x09, 0x95, 0x42, 0x37, 0xa4, 0xfe, 0x76, 0x09, 0x43, 0x38, 0xba, 0xa7, 0x8d, 0xc8,
	0x89, 0x93, 0x12, 0x59, 0x15, 0x58, 0xdd, 0xf4, 0x17, 0xc3, 0x33, 0x80, 0xad, 0x7e, 0xc9, 0xde,
	0x29, 0xb0, 0xbb, 0x8d, 0x3d, 0x12, 0xde, 0x82, 0xcf, 0xe3, 0x83, 0x30, 0x7a, 0x85, 0x17, 0x60,
	0x25, 0xb4, 0x0d, 0x72, 0x7c, 0x7d, 0x32, 0xfb, 0xe9, 0xe4, 0x41, 0x29, 0xa9, 0x62, 0x59, 0x50,
	0xd2, 0x2e, 0x4c, 0x53, 0x70, 0xf8, 0x32, 0x5a, 0xf0, 0x39, 0xba, 0xf0, 0x2f, 0xa2, 0x52, 0xd4,
	0x6c, 0x84, 0x1e, 0x4c, 0xf6, 0x6a, 0x62, 0x46, 0x0b, 0x7a, 0x93, 0x0e, 0x98, 0xe8, 0x0f, 0x45,
	0xee, 0x5c, 0x99, 0xd5, 0xc2, 0x83, 0x28, 0xcc, 0x9e, 0x5e, 0x81, 0x3b, 0x58, 0xe2, 0x04, 0xc6,
	0x4f, 0xf5, 0x26, 0xab, 0x44, 0xc1, 0x46, 0xad, 0xe0, 0xeb, 0x3c, 0x27, 0xad, 0x99, 0x81, 0xff,
	0xc1, 0x7e, 0xcc, 0x44, 0xc5, 0xcc, 0x37, 0xa7, 0xfb, 0xda, 0xcd, 0x77, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x32, 0x8f, 0x63, 0xe6, 0xc8, 0x01, 0x00, 0x00,
}
